name: analysis
channels:
    - conda-forge
dependencies:
  - root
  - pip
  - uproot3
  - uproot
  - awkward
  - pandas
  - numpy
  - matplotlib
  - lmfit
  - scikit-learn
  - aiohttp
  - pip:
    - vector
    - jupyterlab_latex
    - jupyter
